server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      force: true
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB

aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}     # 여기에 발급받은 AWS 액세스 키 ID를 넣습니다.
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY} # 여기에 발급받은 AWS 비밀 액세스 키를 넣습니다.
  region: ap-northeast-2                   # S3 버킷과 DynamoDB 테이블이 생성된 AWS 리전을 넣습니다.
  # (예: 서울 리전은 ap-northeast-2)
  s3:
    bucketName: smresumebucket # 2단계에서 생성한 S3 버킷 이름을 넣습니다.
  dynamodb:
    tableName: resume-analysis-results       # 3단계에서 생성한 DynamoDB 테이블 이름을 넣습니다.

#2. SpringBoot Environment Setting
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/smresume?serverTimezone=Asia/Seoul
    username: root
    password: 1234
#Mybatis Setting
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${client-id}
            client-secret: ${client-secret}
            scope:
              - account_email
              - profile_nickname
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: client_secret_post

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
mybatis:
  type-aliases-package: me.kwakinsung.smresume.app.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

#4. Logging Setting
logging:
  level:
    root: info
    org.springframework.web.socket.messaging: debug
    org.springframework.messaging.simp: debug
    # OpenAI API 관련 로깅 (필요에 따라 조절)
    org.springframework.web.client.RestTemplate: debug
    sm.ac.controller.sm.ac.app.controller.ResumeController: debug
openai:
  api-key: ${openai.api-key}